services:
  - type: web
    name: your-service
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y python3-pip
      pip3 install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app